config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#new'

  get 'inloggen', to: 'sessions#new', as: 'inloggen'
  get 'aanmelden', to: 'users#new', as: 'aanmelden'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users, only: [:new, :show, :create]
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  before_save { email.downcase! }
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user


  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def log_in(user)
    session[:user_id] = user.id
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    #authenticate before saving. :authenticate method
    # comes with has_secure_password
    user = User.find_by_email(params[:email].downcase)
    if user && user.authenticate(params[:password])
      log_in(user)
      redirect_to user
    else
      flash.now.alert = "Inloggen mislukt. Nog eens proberen?"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Je bent uitgelogd"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.signup_confirmation(@user).deliver
      log_in(@user)
      redirect_to @user
    else
      render "new" #todo change to better ending
    end
  end


private

  def user_params
   params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar_links.erb
<!--Links in the left part of the navigation bar-->
<li><a href="#">Pagina 1</a></li>
<li class='divider'></li>
<li><a href="#">Page 2</a></li>
<li class='divider'></li>

app/views/layouts/_navigation.html.erb
<nav class="top-bar" data-topbar>


  <!-- title/logo -->
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Starter App Login", root_path %></h1>
    </li>

    <!-- Menu Button on small screens -->
    <li class="toggle-topbar"><a href="#"><span>Menu</span></a></li>
  </ul>

  <!--start section left-->
  <section class="top-bar-section">
    <ul class="left">
      <li class="active"><%=link_to "Home", root_path %></li>
      <%= render 'layouts/navbar_links' %>
    </ul>
  </section>
  <!--end section left-->

  <!--start section right-->
  <section class="top-bar-section">
    <ul class="right">
      <!--User header: select what links to show-->
      <div id="user-header">
        <% if current_user %>
            <li><a> <%= current_user.email  %> </a></li>

            <li><%= link_to "log uit", logout_path, method: :delete %></li>
        <% else %>
            <li><%= link_to "Maak je account ", aanmelden_path %></li>
            <li><%= link_to "log in", inloggen_path, id: "see_me" %></li>
        <% end %>
      </div> <!--end user header -->
    </ul> <!--close right ul-->
  </section>
  <!--end section right-->

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!--Fonts & icons -->
    <link href='https://fonts.googleapis.com/css?family=Fredericka+the+Great|Raleway:400,300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css">
    <link href='https://fonts.googleapis.com/css?family=Cabin+Sketch' rel='stylesheet' type='text/css'>

    <!--Required for Foundation-->
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

</head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <!--Main container with yielded content page and messages-->
    <div id="playfield">
      <%= yield %>
      <div id="messages">
        <% flash.each do |name, message| %>
            <%= content_tag :div, message, id: "flash#{name}" %>
        <% end %>
      </div>
    </div>
    <!-- Close main container "Playfield" -->

  </body>

</html>

app/views/users/new.html.erb
<h1>Account maken</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
      <div class="error_messages">
        <p>Oeps! Er klopt iets niet :-( </p>
        <ul><% @user.errors.full_messages.each do |message| %>
            <small><li><%= message %></li></small>
          <% end %>
        </ul>
      </div>
  <% end %>

  <div class="loginfield" style="padding-top: 10px">
    <div id="label"><%= f.label :email, autofocus: true %></div>
    <%= f.email_field :email %>
  </div>

  <div class="loginfield">
   <div id="label"> <%= f.label :password, "Kies wachtwoord" %> </div>
    <%= f.password_field :password %>
  </div>

  <div class="loginfield">
    <div id="label"><%= f.label :password_confirmation, "Herhaal wachtwoord" %></div>
    <%= f.password_field :password_confirmation %>
  </div>


  <ul class="button-group">
    <li><%= f.submit "Maak mijn account", class: "button tiny"%></li>
    <li> <%= link_to " of log meteen in als je al een account hebt", inloggen_path, class: "button secondary tiny" %></li>
  </ul> <!--  button-group end -->
<% end %>

app/views/users/show.html.erb
<h1>
  Welkom!
</h1>
 <!-- Stub view for show action. To be replaced with relevant profile data after implementing CanCanCan access rights-->
<p>Veel plezier met in- en uitloggen</p>

<p>(In een echte app kom je nu op een echte pagina.)</p>